services:
  - type: web
    name: bfs-backend
    rootDir: server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
